name: learn-github-actions
on: [push]
jobs:
   giving_it_an_OS:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master
    - name: Update diagram
      id: make_diagram
      uses: githubocto/repo-visualizer@0.7.1
      with:
         github_token: ${{ secrets.DOWNLOAD_SECRET }}
         output_file: output-diagram.svg
         artifact_name: my-diagram
    - name: Get artifact
      uses: actions/download-artifact@v2
      with:
         github_token: ${{ secrets.DOWNLOAD_SECRET }}
         name: "my-diagram"
         path: "downloads"
    

    
